---
driver:
  network:
    - ['forwarded_port', { guest: 9999, host: 9999 } ]
  customize:
    memory: 4096
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: test/data_bags
  encrypted_data_bag_secret_key_path: test/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - 'looker'
    attributes:
      looker:
        # Get these from your looker account Rep
        startup_script_url: "https://s3.amazonaws.com/download.looker.com/aeHee2HiNeekoh3uIu6hec3W/looker"
        jar_file_url: "https://s3.amazonaws.com/download.looker.com/aeHee2HiNeekoh3uIu6hec3W/looker-latest.jar"
