---
driver:
  network:
    - ['forwarded_port', { guest: 9999, host: 9999 } ]
  customize:
    memory: 4096
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - 'apt'
      - 'looker'
    attributes:
      looker:
        startup_args: "--ssl-keystore=/home/looker/looker/.ssl/looker.self.signed.jks --ssl-keystore-pass=''"
        startup_script: 'https://s3.amazonaws.com/download.looker.com/aeHee2HiNeekoh3uIu6hec3W/looker'
        jar_file: 'https://s3.amazonaws.com/download.looker.com/aeHee2HiNeekoh3uIu6hec3W/looker-latest.jar'
