name             'looker'
maintainer       'James Awesome'
maintainer_email 'awesome@shopkeep.com'
license          'All rights reserved'
description      'Installs/Configures looker'
long_description 'Installs/Configures looker'
version          '0.1.0'

depends 'apt'
depends 'java'
