name             'looker'
maintainer       'James Awesome'
maintainer_email 'awesome@shopkeep.com'
license          'All rights reserved'
description      'Installs/Configures looker'
long_description 'Installs/Configures looker'
version          '0.2.4'

depends 'apt'
depends 'java'
depends 'newrelic', '~> 2.4.0'
depends 'ohai'